# https://taskfile.dev

version: "3"

output: "prefixed"

env:
  YOMO_LOG_LEVEL: error
  # set the following environment values on production mode
  # YOMO_ENV: production
  # YOMO_TLS_CACERT_FILE: "../../test/tls/ca.crt"
  # YOMO_TLS_CERT_FILE: "../../test/tls/client.crt"
  # YOMO_TLS_KEY_FILE: "../../test/tls/client.key"

tasks:
  run:
    desc: run
    deps: [source, sfn, zipper]

  # example cleanup
  clean:
    desc: cleanup
    cmds:
      - rm -rf ./bin

  zipper:
    desc: run zipper
    cmds:
      - "go run zipper/main.go"
    env:
      YOMO_LOG_LEVEL: error
      YOMO_ZIPPER_WORKFLOW: ./zipper/workflow.yaml
      # set the following environment values on production mode
      # YOMO_ENV: production
      # YOMO_TLS_CERT_FILE: "../../test/tls/server.crt"
      # YOMO_TLS_KEY_FILE: "../../test/tls/server.key"

  source-build:
    desc: build source
    cmds:
      - "go build -o ./bin/source{{exeExt}} source/main.go"

  source:
    desc: run source
    deps: [source-build]
    cmds:
      - "go build -o ./bin/source{{exeExt}} source/main.go"
      - "./bin/source{{exeExt}}"

  sfn:
    desc: run stream functions
    deps: [sfn-1, sfn-2, sfn-3a, sfn-3b]

  sfn-1:
    desc: run stream functions 1
    cmds:
      - "go build -o ./bin/sfn-1{{exeExt}} ./stream-fn-1/app.go"
      - "./bin/sfn-1{{exeExt}}"

  sfn-2:
    desc: run stream functions 2
    cmds:
      - "go build -o ./bin/sfn-2{{exeExt}} ./stream-fn-2/app.go"
      - "./bin/sfn-2{{exeExt}}"

  sfn-3a:
    desc: run stream functions 3a
    cmds:
      - "go build -o ./bin/sfn-3a{{exeExt}} ./stream-fn-3a/app.go"
      - "./bin/sfn-3a{{exeExt}}"

  sfn-3b:
    desc: run stream functions 3b
    cmds:
      - "go build -o ./bin/sfn-3b{{exeExt}} ./stream-fn-3b/app.go"
      - "./bin/sfn-3b{{exeExt}}"
